adding missing hass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mila/__init__.py", line 81, in async_setup_entry
    device_registry = await hass.helpers.device_registry.async_get()
TypeError: async_get() missing 1 required positional argument: 'hass'